-- Run this ENTIRE script at once in phpMyAdmin SQL tab
-- Existing columns will just show a warning, new ones will be added

ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `quotation_url` VARCHAR(500) DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `invoice_type` VARCHAR(50) DEFAULT 'no-tax-invoice';
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `private_transport_name` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `origin_branch` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `destination_branch` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `preferred_time_slot` VARCHAR(20) DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `total_price` DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `graphics_notes` TEXT DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `design_files` TEXT DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `production_workflow` TEXT DEFAULT NULL;
ALTER TABLE `orders` ADD COLUMN IF NOT EXISTS `material` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `order_items` ADD COLUMN IF NOT EXISTS `bow_type` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `order_items` ADD COLUMN IF NOT EXISTS `bow_colors` TEXT DEFAULT NULL;
ALTER TABLE `order_items` ADD COLUMN IF NOT EXISTS `price` DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE `order_items` ADD COLUMN IF NOT EXISTS `total_price_item` DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE `order_items` ADD COLUMN IF NOT EXISTS `item_id` INT(11) DEFAULT NULL;

ALTER TABLE `order_payments` ADD COLUMN IF NOT EXISTS `receiving_bank` VARCHAR(255) DEFAULT NULL;
