CREATE TABLE `price_estimations_sales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `estimate_id` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `estimation_date` date DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `customer_name` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `customer_phone` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `customer_line` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `customer_email` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `sales_owner_id` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `job_name` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `product_category` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `product_type` varchar(100) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `quantity` int(11) DEFAULT 0,
  `budget` decimal(12,2) DEFAULT 0.00,
  `price` decimal(12,2) DEFAULT 0.00,
  `status` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT 'ยื่นคำขอประเมิน',
  `revision_count` int(11) DEFAULT 0,
  `notes` text COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `details` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
