// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rirhrmjnxgjxwokqvwhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcmhybWpueGdqeHdva3F2d2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDU5MDYsImV4cCI6MjA3Mjg4MTkwNn0.-qLS9tUw8JCCkx2Wi3SHcpwWYF0BA2G0guATFO8MWCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});